#!/usr/bin/env bash
set -Eeuo pipefail

: "${INSTALL_DIR:?INSTALL_DIR is required}"
settings_json="${CODEX_LINUX_FEATURE_SETTINGS_JSON:-}"
[ -n "$settings_json" ] || settings_json='{}'
target="$INSTALL_DIR/.codex-linux/features/community-profile-isolation/profile-config.sh"

[[ -f "$target" ]] || {
  printf 'Community profile config target is missing: %s\n' "$target" >&2
  exit 69
}

node - "$settings_json" "$target" <<'NODE'
const fs = require("node:fs");
const [raw, target] = process.argv.slice(2);
const settings = JSON.parse(raw || "{}");
const defaults = {
  codexHome: "~/.codex-community",
  electronUserDataPath: "~/.config/Codex-Community",
};
function validate(value, key) {
  const resolved = value == null ? defaults[key] : value;
  if (typeof resolved !== "string" || resolved.length === 0) {
    throw new Error(`${key} must be a non-empty string`);
  }
  if (!(resolved === "~" || resolved.startsWith("~/") || resolved.startsWith("/"))) {
    throw new Error(`${key} must be ~/... or an absolute path`);
  }
  if (/[\u0000\r\n]/.test(resolved)) {
    throw new Error(`${key} contains unsupported control characters`);
  }
  return resolved;
}

function shellQuote(value) {
  return "'" + value.replaceAll("'", "'\\''") + "'";
}
const codexHome = validate(settings.codexHome, "codexHome");
const electron = validate(settings.electronUserDataPath, "electronUserDataPath");
fs.writeFileSync(
  target,
  [
    "# Generated by community-profile-isolation/stage.sh",
    `CODEX_COMMUNITY_CODEX_HOME_SPEC=${shellQuote(codexHome)}`,
    `CODEX_COMMUNITY_ELECTRON_USER_DATA_SPEC=${shellQuote(electron)}`,
    "",
  ].join("\n"),
);
NODE
